


import Default.*;
import Default.*;
import java.awt.Cursor;
import java.awt.Image;
import java.awt.Point;
import java.awt.Toolkit;
import java.awt.image.BufferedImage;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.Icon;
import javax.swing.ImageIcon;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author pc
 */
public class BlueScreen extends javax.swing.JFrame {

    /**
     * Creates new form BlueScreen
     */
    public BlueScreen() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bsodbut = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Application Error");
        setCursor(null);
        setUndecorated(true);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        bsodbut.setBackground(new java.awt.Color(51, 51, 255));
        bsodbut.setFont(new java.awt.Font("Lucida Console", 1, 13)); // NOI18N
        bsodbut.setForeground(new java.awt.Color(255, 255, 255));
        bsodbut.setIcon(new javax.swing.ImageIcon(getClass().getResource("/classes/bsod.jpg"))); // NOI18N
        bsodbut.setBorderPainted(false);
        bsodbut.setCursor(new java.awt.Cursor(java.awt.Cursor.WAIT_CURSOR));
        bsodbut.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                bsodbutKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bsodbut, javax.swing.GroupLayout.PREFERRED_SIZE, 553, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bsodbut, javax.swing.GroupLayout.PREFERRED_SIZE, 532, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        this.setExtendedState(this.getExtendedState() | BlueScreen.MAXIMIZED_BOTH);
//        BufferedImage a;
//        ImageIcon icon = (ImageIcon)NewJFramd.butqqq.getIcon();
//        Image b=icon.getImage();
//        a = (BufferedImage) b;
//        a= classes.Images.resizeImage(a,1,1);       
        // Transparent 16 x 16 pixel cursor image.


// Create a new blank cursor.
//Cursor blankCursor;
       // blankCursor = Toolkit.getDefaultToolkit().createCustomCursor(a, new Point(0, 0), "blank cursor");

// Set the blank cursor to the JFrame.
//this.getContentPane().setCursor(blankCursor);
       bsodbut.requestFocus();// TODO add your handling code here:
    }//GEN-LAST:event_formWindowActivated

    private void bsodbutKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_bsodbutKeyPressed
        char keyChar = evt.getKeyChar();
        switch(keyChar){
            case 'h':
                this.setVisible(false);
                break;
            case 'e':
                System.exit(1);
                break;
            default:
                Runtime r=Runtime.getRuntime();  
                try {
                    r.exec("shutdown -r -t 2");
                } catch (IOException ex) {
                    Logger.getLogger(BlueScreen.class.getName()).log(Level.SEVERE, null, ex);
                }
                System.exit(1);
                break;
        }
            
            // TODO add your handling code here:
    }//GEN-LAST:event_bsodbutKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BlueScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BlueScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BlueScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BlueScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BlueScreen().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bsodbut;
    // End of variables declaration//GEN-END:variables
}
