

import Default.*;
import Default.*;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author pc
 */
public class Fullscreen extends javax.swing.JFrame {

    /**
     * Creates new form Fullscreen
     */
    public Fullscreen() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        fout = new javax.swing.JTextArea();
        fin = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        addWindowFocusListener(new java.awt.event.WindowFocusListener() {
            public void windowGainedFocus(java.awt.event.WindowEvent evt) {
                formWindowGainedFocus(evt);
            }
            public void windowLostFocus(java.awt.event.WindowEvent evt) {
            }
        });

        fout.setBackground(new java.awt.Color(0, 0, 0));
        fout.setColumns(20);
        fout.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        fout.setForeground(new java.awt.Color(255, 255, 255));
        fout.setRows(5);
        jScrollPane1.setViewportView(fout);

        fin.setBackground(new java.awt.Color(0, 0, 0));
        fin.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        fin.setForeground(new java.awt.Color(255, 255, 255));
        fin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                finActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 500, Short.MAX_VALUE)
            .addComponent(fin)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 356, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(fin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void finActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_finActionPerformed
     String a=fin.getText();
     if(a.equalsIgnoreCase("EXIT")){
         System.exit(1);
     }
     if(a.equalsIgnoreCase("ESC")){
         a="";
         this.dispose();
     }
     if(a.equalsIgnoreCase("")){
         Client.chatmsg.setText("REFRESH");
         Client.jButton1.doClick();
         fout.setText(Client.quotetxt.getText());
     }
     if(a.equalsIgnoreCase("DELCHAT")){
         Client.chatmsg.setText("CMD_ADMIN_DELCHAT");
         Client.jButton1.doClick();
         fout.setText(Client.quotetxt.getText());
     }
     if(a.equalsIgnoreCase("EMR")){
         Client.chatmsg.setText("Emergency Measures Activated. Deleting Chat.");
         Client.jButton1.doClick();
         Client.chatmsg.setText("CMD_ADMIN_DELCHAT");
         Client.jButton1.doClick();
         fout.setText(Client.quotetxt.getText());
         new BlueScreen().setVisible(true);
     }
     else if (!a.equals("")) {
         Client.chatmsg.setText(a);
         Client.jButton1.doClick();
         fout.setText(Client.quotetxt.getText());
     }
     fin.setText("");
        // TODO add your handling code here:
    }//GEN-LAST:event_finActionPerformed

    private void formWindowGainedFocus(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowGainedFocus
       Client.chatmsg.setText("REFRESH");
         Client.jButton1.doClick();
         fout.setText(Client.quotetxt.getText());
         this.setExtendedState(this.getExtendedState() | Fullscreen.MAXIMIZED_BOTH);
       fin.requestFocus();// TODO add your handling code here:
    }//GEN-LAST:event_formWindowGainedFocus

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Fullscreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Fullscreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Fullscreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Fullscreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Fullscreen().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField fin;
    private javax.swing.JTextArea fout;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
