


//import java.awt.Graphics;
//import java.awt.image.ImageObserver;
//import java.awt.image.ImageProducer;
import Default.*;
import Default.*;
import java.io.PrintWriter;
import java.net.InetAddress;
import java.net.Socket;
import java.util.Scanner;
import java.awt.*;
//import javax.swing.*;

/**
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 * Hello
 * This is DexChat
 * I am the developer of this program
 */
/**
 *
 * @author pc
 */
public class Launcher extends javax.swing.JFrame {
public static int token,serverchk,clchk=0;;
public static String[] ip,name,pass,online;
public static Launcher launcher=new Launcher();
public static boolean errorCheck=true;

                

    /**
     * Creates new form Launcher
     */
    public Launcher() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton3 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        serveradd = new javax.swing.JTextField();
        PICLABEL = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        hostname = new javax.swing.JTextField();
        username = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        portname = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        passname = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        unid = new javax.swing.JTextField();

        jButton3.setText("jButton3");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton2.setText("Stop Local Server");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        serveradd.setEditable(false);
        serveradd.setText("localhost");

        PICLABEL.setIcon(new javax.swing.ImageIcon(getClass().getResource("/LoginSys/AirPort.png"))); // NOI18N
        PICLABEL.setText("jLabel6");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Welcome");
        setBounds(new java.awt.Rectangle(300, 200, 354, 175));
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jLabel1.setText("Server Name/IP");

        hostname.setText("localhost");
        hostname.setNextFocusableComponent(passname);
        hostname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hostnameActionPerformed(evt);
            }
        });

        username.setNextFocusableComponent(hostname);
        username.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usernameActionPerformed(evt);
            }
        });

        jLabel2.setText("Your name");

        jButton1.setText("Create new chatbox");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        portname.setEditable(false);
        portname.setText("1234");

        jLabel3.setText("Port number");

        passname.setText("default");
        passname.setNextFocusableComponent(jButton1);
        passname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passnameActionPerformed(evt);
            }
        });

        jLabel4.setText("Password");

        jLabel5.setText("Unique Server ID");

        jButton4.setText("Help");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        unid.setEditable(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(11, 11, 11)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(hostname, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(portname)
                            .addComponent(username)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(11, 11, 11)
                        .addComponent(passname))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(4, 4, 4)
                                .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 254, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(unid)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(username, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(hostname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(portname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(passname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(unid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton4))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if(clchk==0)
        {
            Thread clientthread=new clein();
            clientthread.start();
            clchk=1;
        }
        
        if(serverchk==0)
        {
            Thread serverthread=new serve();
        serverthread.start();
        serverchk=1;
        }
        launcher.setVisible(false);
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
      username.setText(Launcher.username.getText());
        
        String passq=Launcher.hostname.getText();
  passq=passq.replace('A', '0');
  passq=passq.replace('S', '1');
  passq=passq.replace('D', '2');
  passq=passq.replace('F', '3');
  passq=passq.replace('G', '4');
  passq=passq.replace('H', '5');
  passq=passq.replace('J', '6');
  passq=passq.replace('K', '7');
  passq=passq.replace('L', '8');
  passq=passq.replace('Z', '9');
  passq=passq.replace("X", ".");
  
  hostname.setText(passq);
         String username1="";
        try{
  InetAddress ownIP=InetAddress.getLocalHost();
 username1=ownIP.getHostAddress();
  
  }catch (Exception e){
  
  }
        int port = Integer.parseInt(portname.getText());
String temp1=passq;

        System.out.println("Welcome to the DexChat Client\n");
Socket s = DexCCL.getSocket(port); 
try
{
System.out.println("Connected on port " + port);
Scanner in =new Scanner(s.getInputStream());
PrintWriter out = new PrintWriter(s.getOutputStream(),true); 




out.println(username1);
out.println(passname.getText());
String app=in.nextLine();
out.println("CMD_ADMIN_EXIT"); 
//if(app.equalsIgnoreCase("APPROVE"))
        {
            
        
    

}
//else if(app.equalsIgnoreCase("DISAPPROVE"))
{
    //quotetxt.setText("Connection Failed! The possible reasons are:\n\t1. You entered a wrong password.\n\t2. The server version is not upto date.\nTry closing the chatbox and re-entering the details.\n Exiting in(seconds) ");
    //chatmsg.setEditable(false);
    //jButton1.setEnabled(false);
    //jButton3.setEnabled(false);
    //for(int i=30;i>0;i--)
    //{
     //   
     //   quotetxt.append("i\t");
     
     //this.wait(1000);
   // }
    
}
// disconnect from the server
out.println("CMD_EXIT"); 
//System.out.println(in.nextLine());

s.close(); 






}
catch (Exception e)
{
}
        // TODO add your handling code here:
       // your handling code here:
       
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
       new Connector().setVisible(true); // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        Image icon=Image1.iconToImage(PICLABEL.getIcon());
        //Image icon = Toolkit.getDefaultToolkit().createImage("C:\\Screenshots\\AirPort.png");        
       this.setIconImage(icon);        
        try{
  InetAddress ownIP=InetAddress.getLocalHost();
  String passq=ownIP.getHostAddress();
//  passq=passq.replace('0', 'A');
//  passq=passq.replace('1', 'S');
//  passq=passq.replace('2', 'D');
//  passq=passq.replace('3', 'F');
//  passq=passq.replace('4', 'G');
//  passq=passq.replace('5', 'H');
//  passq=passq.replace('6', 'J');
//  passq=passq.replace('7', 'K');
//  passq=passq.replace('8', 'L');
//  passq=passq.replace('9', 'Z');
//  passq=passq.replace(".", "X");
  unid.setText(passq);
  serveradd.setText(ownIP.getHostAddress());
  }catch (Exception e){
  serveradd.setText("Exception caught ="+e.getMessage());
  
  } // TODO add your handling code here:
    }//GEN-LAST:event_formWindowOpened

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        new help().setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void usernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usernameActionPerformed
jButton1.doClick();        // TODO add your handling code here:
    }//GEN-LAST:event_usernameActionPerformed

    private void hostnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hostnameActionPerformed
jButton1.doClick();        // TODO add your handling code here:
    }//GEN-LAST:event_hostnameActionPerformed

    private void passnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passnameActionPerformed
jButton1.doClick();          // TODO add your handling code here:
    }//GEN-LAST:event_passnameActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Launcher.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Launcher.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Launcher.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Launcher.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                Launcher launcher1=new Launcher();
                launcher1.setVisible(true);
                launcher=launcher1;
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JLabel PICLABEL;
    public static javax.swing.JTextField hostname;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    public static javax.swing.JTextField passname;
    public static javax.swing.JTextField portname;
    public static javax.swing.JTextField serveradd;
    private javax.swing.JTextField unid;
    public static javax.swing.JTextField username;
    // End of variables declaration//GEN-END:variables
}
